version: '3.1'
services:
  ewm-service:
    build: main-server
    image: main-server-image
    container_name: "main-server-container"
    ports:
      - "8080:8080"
    depends_on:
      - statistic-server
      - db
    environment:
      - STATISTIC-SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/exploredb
      - POSTGRES_DB=exploredb
      - POSTGRES_USER=programmer
      - POSTGRES_PASSWORD=1234

  statistic-server:
    build: statistic-server
    image: statistic-server-image
    container_name: "statistic-server-container"
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/exploredb
      - POSTGRES_DB=exploredb
      - POSTGRES_USER=programmer
      - POSTGRES_PASSWORD=1234

  db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=exploredb
      - POSTGRES_USER=programmer
      - POSTGRES_PASSWORD=1234
